version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  phantomjs:
    image: wernight/phantomjs
    ports:
      - 8910:8910
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"